from __future__ import annotations

import random
import string
import unittest
from datetime import date

from questions_agent_platform.pipeline.api import _get_query_date


class InputFuzzGuardrailTests(unittest.TestCase):
    def test_get_query_date_accepts_valid_iso_date(self) -> None:
        self.assertEqual(date(2026, 2, 16), _get_query_date(["2026-02-16"]))

    def test_get_query_date_rejects_random_noise(self) -> None:
        rng = random.Random(7262026)
        alphabet = string.ascii_letters + string.digits + " _/:\\.-+TZ"

        failures = 0
        for _ in range(250):
            s = "".join(rng.choice(alphabet) for _ in range(rng.randint(1, 24)))
            # Skip any accidental valid ISO date strings generated by chance.
            try:
                date.fromisoformat(s)
            except Exception:
                pass
            else:
                continue
            try:
                _get_query_date([s])
            except ValueError:
                continue
            except Exception as exc:  # pragma: no cover - explicit failure path
                self.fail(f"unexpected exception for value {s!r}: {exc}")
            else:
                failures += 1

        self.assertEqual(0, failures, "some random non-ISO inputs were accepted as dates")


if __name__ == "__main__":
    unittest.main()
